# Generated by Django 4.2.1 on 2023-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(default="default.png", upload_to="productos"),
        ),
    ]
