# Generated by Django 4.2.1 on 2023-06-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_donacion_alter_coupon_active_alter_coupon_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donacion",
            name="rut",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="donacion",
            name="rut_cifrado",
            field=models.CharField(max_length=64),
        ),
    ]
