# Generated by Django 4.2.1 on 2023-06-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_donacion_rut_alter_donacion_rut_cifrado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donacion",
            name="rut",
            field=models.CharField(max_length=12),
        ),
    ]
