# Generated by Django 4.2.1 on 2023-06-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_donacion_rut"),
    ]

    operations = [
        migrations.AddField(
            model_name="donacion",
            name="rut_bcrypt",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
