# Generated by Django 4.2.1 on 2023-07-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onepiececapitulomanga',
            options={},
        ),
        migrations.RemoveField(
            model_name='onepiececapitulomanga',
            name='created',
        ),
        migrations.RemoveField(
            model_name='onepiececapitulomanga',
            name='modified',
        ),
    ]
