# Generated by Django 4.2.1 on 2023-07-07 06:46

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_onepiececapitulomanga_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onepiececapitulomanga',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='onepiececapitulomanga',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onepiececapitulomanga',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
