# Generated by Django 4.2.1 on 2023-07-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='onepiececapitulomanga',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='onepiece_covers/'),
        ),
    ]
