# Generated by Django 4.2.1 on 2023-07-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_onepiececapitulomanga_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
        migrations.RemoveField(
            model_name='onepiececapitulomanga',
            name='id',
        ),
        migrations.AlterField(
            model_name='onepiececapitulomanga',
            name='capitulo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
